numbers = [10, 20, 30, 40, 50]
print(f"Original list: {numbers}")
print(f"Length: {len(numbers)}")
last_element = numbers.pop()
print(f"Popped element: {last_element}")
print(f"After pop(): {numbers}")
print(f"Length: {len(numbers)}")
numbers.pop()
numbers.pop()
print(f"After two more pops: {numbers}")
print(f"Length: {len(numbers)}")
popped_value = numbers.pop(0)
print(f"Popped element at index 0: {popped_value}")
print(f"After pop(0): {numbers}")
